- file:
    path: configurations/NewHorizons/Configuration.xml
    change:
        - insert: 8
          highlight: true
          snippet: snippetAddAdapterAndReceiver
- snippet:
    name: snippetAddAdapterAndReceiver
    markup: xml
    context: 50