- file:
    path: src/main/webapp/index.html
    change: add
- file:
    path: src/main/resources/DeploymentSpecifics.properties
    change:
      - insert: 3
        snippet: deploymentSpecificsAddCustomView
        highlight: true
- snippet:
    name: deploymentSpecificsAddCustomView
    markup: none
    context: 50
