- file:
    path: configurations/NewHorizons/Configuration.xml
    change:
        - old: 1
          new: 12
          snippet: addSenderInsertTableVisit
- snippet:
    name: addSenderInsertTableVisit
    markup: xml
    context: 0