- predecessor: v500
- file:
    path: Frank2Example1/Example1a/Configuration.xml
    change:
      - snippet: adapterReceiverPipeline
        old: 4
        new: 1
      - snippet: adapterReceiverPipeline
        old: 1
        new: 1
      - snippet: adapterReceiverPipeline
        old: 1
        new: 1
      - snippet: adapterReceiverPipeline
        old: 1
        new: 1
- snippet:
    name: adapterReceiverPipeline
    markup: XML
    context: 50