- file:
    path: pom.xml
    change:
      - insert: 6
        snippet: pomFiltering
        highlight: true
- file:
    path: src/main/resources/StageSpecifics_LOC.properties
    change: add
- file:
    path: src/test/testtool/scenario01.properties
    change: add
- file:
    path: src/test/testtool/scenario01/in.txt
    change: add
- file:
    path: src/test/testtool/scenario01/out.txt
    change: add
- snippet:
    name: pomFiltering
    markup: xml
    context: 4