- predecessor: v460
- file:
    path: configurations/NewHorizons/booking2destinations.xsl
    change: add
- file:
    path: configurations/NewHorizons/Configuration.xml
    change:
        - old: 1
          new: 1
          highlight: true
          snippet: addXsltPipe
        - insert: 6
          highlight: true
          snippet: addXsltPipe
- snippet:
    name: addXsltPipe
    markup: xml
    context: 5