- file:
    path: configurations/NewHorizons/Configuration.xml
    change:
        - old: 1
          new: 2
          highlight: true
          snippet: namedQueryParameters
- snippet:
    name: namedQueryParameters
    markup: xml
    context: 5
