- file:
    path: configurations/NewHorizons/Configuration.xml
    change:
        - old: 1
          new: 1
          highlight: true
          snippet: refSenderPipe
        - insert: 13
          highlight: true
          snippet: addSenderPipe
- snippet:
    name: refSenderPipe
    markup: xml
    context: 2
- snippet:
    name: addSenderPipe
    markup: xml
    context: 2