- file:
    path: configurations/NewHorizons/Configuration.xml
    change:
        - old: 1
          new: 1
          highlight: true
          snippet: addFixedResultInvalidBooking
        - insert: 5
          highlight: true
          snippet: addFixedResultInvalidBooking
- snippet:
    name: addFixedResultInvalidBooking
    markup: xml
    context: 5