- predecessor: v500
- file:
    path: Frank2Example1/Example1a/Configuration.xml
    change:
      - snippet: pipeline
        old: 8
        new: 1
      - snippet: pipeline
        old: 2
        new: 1
- snippet:
    name: pipeline
    markup: XML
    context: 50
